# Generated by Django 6.0.4 on 2026-04-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=128)),
                ("contact_code", models.CharField(blank=True, default="", max_length=64)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("emergency_type", models.CharField(choices=[("trapped", "Trapped"), ("medical", "Medical"), ("unresponsive", "Unresponsive"), ("fire", "Fire"), ("flood", "Flood"), ("other", "Other")], default="other", max_length=32)),
                ("description", models.TextField(blank=True, default="")),
                ("reporter_name", models.CharField(blank=True, default="", max_length=128)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="restrictions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="incident",
            name="risk_grade",
            field=models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="high", max_length=16),
        ),
    ]
